#!/usr/bin/env bash
#
# regen-routes.sh — generate friendly subfolder routes for containers.
#
# For every running container on the Docker network whose name starts with
# "<PREFIX>_" (PREFIX defaults to "sanjeman"), derive a URL path by stripping
# the prefix and turning "_" into "/":
#
#   sanjeman_sanjup_api   ->  /sanjup/api
#   sanjeman_core         ->  /core
#
# One nginx location is emitted per container (longest path first, so nested
# routes win) and nginx is reloaded. The existing subdomain and literal-name
# (/sanjeman_sanjup_api) routes keep working. Re-run this after you add or
# remove a container — it is fully automatic, no per-container config.
#
# Override defaults via env:
#   APP_ROUTE_PREFIX=sanjeman  APP_DOCKER_NETWORK=app  NGINX_CONTAINER=nginx
#
set -eo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONF_DIR="$SCRIPT_DIR/src/conf.d/app-routes"
OUT_FILE="$CONF_DIR/app-routes.conf"

NGINX_CONTAINER="${NGINX_CONTAINER:-nginx}"
NETWORK="${APP_DOCKER_NETWORK:-app}"
PREFIX="${APP_ROUTE_PREFIX:-sanjeman}"

mkdir -p "$CONF_DIR"

# Escape regex metacharacters in a derived path (only "." realistically appears).
escape_regex() { printf '%s' "$1" | sed 's/\./\\./g'; }

# --- gather candidate containers on the network -----------------------------
containers="$(docker network inspect "$NETWORK" \
    --format '{{range .Containers}}{{.Name}}{{"\n"}}{{end}}' 2>/dev/null \
  | grep -E "^${PREFIX}_[A-Za-z0-9._-]+$" || true)"

if [ -z "$containers" ]; then
    echo "No containers matching '${PREFIX}_*' found on network '$NETWORK'."
fi

# --- derive path per container, dedupe, keep longest-first ------------------
# rows: "<zeropadded length>|<path>|<container>"
rows=""
seen=""
while IFS= read -r c; do
    [ -z "$c" ] && continue
    rest="${c#${PREFIX}_}"          # strip "sanjeman_"
    [ -z "$rest" ] && continue      # bare prefix, nothing to map
    path="${rest//_//}"             # "_" -> "/"
    case ",$seen," in
        *",$path,"*) echo "WARN: '/$path' already mapped; skipping '$c'" >&2; continue ;;
    esac
    seen="${seen},$path"
    rows+="$(printf '%05d|%s|%s\n' "${#path}" "$path" "$c")"$'\n'
done <<< "$containers"

# longest path first, so /sanjup/api is matched before /sanjup
mapfile -t sorted < <(printf '%s' "$rows" | grep -v '^$' | sort -rn || true)

# --- emit one nginx location per container ----------------------------------
emit_block() {
    local path="$1" container="$2" rx
    rx="$(escape_regex "$path")"
    cat <<EOF
    # ${container}  ->  /${path}
    # The request path is PRESERVED: the full URI is forwarded unchanged, so
    # this behaves exactly like  <container>.codespacex.ir/<path>. The app is
    # expected to be mounted with /<path> as its route prefix (the subfolder is
    # part of every route in the app).
    location ~ ^/${rx}(/.*)?\$ {
        resolver 127.0.0.11 ipv6=off;

        set \$upstream "${container}";

        proxy_http_version 1.1;
        proxy_set_header Host              \$http_host;
        proxy_set_header Scheme            \$scheme;
        proxy_set_header SERVER_PORT       \$server_port;
        proxy_set_header REMOTE_ADDR       \$remote_addr;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade           \$http_upgrade;
        proxy_set_header Connection        \$connection_upgrade;

        proxy_connect_timeout 300;
        proxy_pass http://\$upstream\$request_uri;
    }
EOF
}

tmp="$(mktemp)"
{
    echo "# AUTO-GENERATED by regen-routes.sh — do not edit by hand."
    echo "# prefix='${PREFIX}'  network='${NETWORK}'"
    echo "# regenerate: ./regen-routes.sh"
    echo
    if [ "${#sorted[@]}" -eq 0 ]; then
        echo "# (no matching containers right now)"
    fi
    for line in "${sorted[@]}"; do
        path="${line#*|}"; path="${path%|*}"    # drop LEN| and |CONTAINER
        container="${line##*|}"                  # after last |
        emit_block "$path" "$container"
    done
} > "$tmp"

# --- validate, then swap in (roll back on failure) --------------------------
backup=""
[ -f "$OUT_FILE" ] && backup="$(mktemp)" && cp "$OUT_FILE" "$backup"
cp "$tmp" "$OUT_FILE"
rm -f "$tmp"

if ! docker exec "$NGINX_CONTAINER" nginx -t >/dev/null 2>&1; then
    echo "ERROR: nginx config test failed; restoring previous config." >&2
    [ -n "$backup" ] && cp "$backup" "$OUT_FILE"
    docker exec "$NGINX_CONTAINER" nginx -t >&2 || true
    rm -f "$backup"
    exit 1
fi
rm -f "$backup"
docker exec "$NGINX_CONTAINER" nginx -s reload

# --- report -----------------------------------------------------------------
echo "Routes regenerated and nginx reloaded:"
if [ "${#sorted[@]}" -gt 0 ]; then
    for line in "${sorted[@]}"; do
        path="${line#*|}"; path="${path%|*}"
        container="${line##*|}"
        printf '  %-22s -> %s\n' "/$path" "$container"
    done
else
    echo "  (none)"
fi
